int  configlinatextbox1callback(int cellno,int i,void *Tmp);
int  configlinabutton1callback(int butno,int i,void *Tmp) ;
void  configlinabutton1init(DIN *B,void *pt) ;
int  configlinabrowser1callback(int item,int i,void *Tmp) ;
void  configlinabrowser1init(DICH *C,void *pt) ;
int  configlinabrowser2callback(int item,int i,void *Tmp) ;
int  configlinabrowser3callback(int item,int i,void *Tmp) ;
int  configlinafslide1callback(double val,int i,void *Tmp) ;
int  configlinafslide2callback(double val,int i,void *Tmp) ;
int  configlinasplbutton1callback(int butno,int i,void *Tmp) ;
void  configlinasplbutton1init(DIL *B,void *pt) ;
int  configlinabutton2callback(int butno,int i,void *Tmp) ;
void  configlinabutton2init(DIN *B,void *pt) ;
int  configlinabutton3callback(int butno,int i,void *Tmp) ;
void  configlinabutton3init(DIN *B,void *pt) ;
int  configlinabrowser4callback(int item,int i,void *Tmp) ;
int  configlinabutton4callback(int butno,int i,void *Tmp) ;
void  configlinabutton4init(DIN *B,void *pt) ;
int configlinainit(void *Tmp) ;
int configlinacleanup(void *Tmp) ;
int configlinaCallBack(void *Tmp,void *tmp) ;
int configlinaResizeCallBack(void *Tmp) ;
int configlinaWaitCallBack(void *Tmp) ;
